package App.entity;
// Generated Mar 20, 2020 11:24:49 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SanPham generated by hbm2java
 */
@Entity
@Table(name = "san_pham", catalog = "management_shop")
public class SanPham implements java.io.Serializable {

	private Integer maSp;
	private ChatLieu chatLieu;
	private DanhMuc danhMuc;
	private LoaiSp loaiSp;
	private TinhTrang tinhTrang;
	private String tenSp;
	private Double giaBan;
	private Integer luotMuaSp;
	private String hinhAnhSp;
	private String moTaSp;
	private Set<HoaDonChiTiet> hoaDonChiTiets = new HashSet<HoaDonChiTiet>(0);

	public SanPham() {
	}

	public SanPham(DanhMuc danhMuc, LoaiSp loaiSp) {
		this.danhMuc = danhMuc;
		this.loaiSp = loaiSp;
	}

	public SanPham(ChatLieu chatLieu, DanhMuc danhMuc, LoaiSp loaiSp, TinhTrang tinhTrang, String tenSp, Double giaBan,
			Integer luotMuaSp, String hinhAnhSp, String moTaSp, Set<HoaDonChiTiet> hoaDonChiTiets) {
		this.chatLieu = chatLieu;
		this.danhMuc = danhMuc;
		this.loaiSp = loaiSp;
		this.tinhTrang = tinhTrang;
		this.tenSp = tenSp;
		this.giaBan = giaBan;
		this.luotMuaSp = luotMuaSp;
		this.hinhAnhSp = hinhAnhSp;
		this.moTaSp = moTaSp;
		this.hoaDonChiTiets = hoaDonChiTiets;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ma_sp", unique = true, nullable = false)
	public Integer getMaSp() {
		return this.maSp;
	}

	public void setMaSp(Integer maSp) {
		this.maSp = maSp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ma_chat_lieu_sp")
	public ChatLieu getChatLieu() {
		return this.chatLieu;
	}

	public void setChatLieu(ChatLieu chatLieu) {
		this.chatLieu = chatLieu;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ma_dm", nullable = false)
	public DanhMuc getDanhMuc() {
		return this.danhMuc;
	}

	public void setDanhMuc(DanhMuc danhMuc) {
		this.danhMuc = danhMuc;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "loai_sp", nullable = false)
	public LoaiSp getLoaiSp() {
		return this.loaiSp;
	}

	public void setLoaiSp(LoaiSp loaiSp) {
		this.loaiSp = loaiSp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tinh_trang")
	public TinhTrang getTinhTrang() {
		return this.tinhTrang;
	}

	public void setTinhTrang(TinhTrang tinhTrang) {
		this.tinhTrang = tinhTrang;
	}

	@Column(name = "ten_sp", length = 45)
	public String getTenSp() {
		return this.tenSp;
	}

	public void setTenSp(String tenSp) {
		this.tenSp = tenSp;
	}

	@Column(name = "gia_ban", precision = 22, scale = 0)
	public Double getGiaBan() {
		return this.giaBan;
	}

	public void setGiaBan(Double giaBan) {
		this.giaBan = giaBan;
	}

	@Column(name = "luot_mua_sp")
	public Integer getLuotMuaSp() {
		return this.luotMuaSp;
	}

	public void setLuotMuaSp(Integer luotMuaSp) {
		this.luotMuaSp = luotMuaSp;
	}

	@Column(name = "hinh_anh_sp", length = 45)
	public String getHinhAnhSp() {
		return this.hinhAnhSp;
	}

	public void setHinhAnhSp(String hinhAnhSp) {
		this.hinhAnhSp = hinhAnhSp;
	}

	@Column(name = "mo_ta_sp", length = 1000)
	public String getMoTaSp() {
		return this.moTaSp;
	}

	public void setMoTaSp(String moTaSp) {
		this.moTaSp = moTaSp;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sanPham")
	public Set<HoaDonChiTiet> getHoaDonChiTiets() {
		return this.hoaDonChiTiets;
	}

	public void setHoaDonChiTiets(Set<HoaDonChiTiet> hoaDonChiTiets) {
		this.hoaDonChiTiets = hoaDonChiTiets;
	}

}
