package App.entity;
// Generated Mar 20, 2020 11:24:49 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TinhTrangHd generated by hbm2java
 */
@Entity
@Table(name = "tinh_trang_hd", catalog = "management_shop")
public class TinhTrangHd implements java.io.Serializable {

	private int idTinhTrangHd;
	private String tinhTrang;
	private Set<HoaDon> hoaDons = new HashSet<HoaDon>(0);

	public TinhTrangHd() {
	}

	public TinhTrangHd(int idTinhTrangHd) {
		this.idTinhTrangHd = idTinhTrangHd;
	}

	public TinhTrangHd(int idTinhTrangHd, String tinhTrang, Set<HoaDon> hoaDons) {
		this.idTinhTrangHd = idTinhTrangHd;
		this.tinhTrang = tinhTrang;
		this.hoaDons = hoaDons;
	}

	@Id

	@Column(name = "id_tinh_trang_hd", unique = true, nullable = false)
	public int getIdTinhTrangHd() {
		return this.idTinhTrangHd;
	}

	public void setIdTinhTrangHd(int idTinhTrangHd) {
		this.idTinhTrangHd = idTinhTrangHd;
	}

	@Column(name = "tinh_trang", length = 45)
	public String getTinhTrang() {
		return this.tinhTrang;
	}

	public void setTinhTrang(String tinhTrang) {
		this.tinhTrang = tinhTrang;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tinhTrangHd")
	public Set<HoaDon> getHoaDons() {
		return this.hoaDons;
	}

	public void setHoaDons(Set<HoaDon> hoaDons) {
		this.hoaDons = hoaDons;
	}

}
