package App.entity;
// Generated Aug 7, 2020 10:34:01 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DanhMuc generated by hbm2java
 */
@Entity
@Table(name = "danh_muc", catalog = "pl9x6o2av23gjabw")
public class DanhMuc implements java.io.Serializable {

	private Integer maDm;
	private String tenDm;
	private Set<SanPham> sanPhams = new HashSet<SanPham>(0);

	public DanhMuc() {
	}

	public DanhMuc(String tenDm) {
		this.tenDm = tenDm;
	}

	public DanhMuc(String tenDm, Set<SanPham> sanPhams) {
		this.tenDm = tenDm;
		this.sanPhams = sanPhams;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ma_dm", unique = true, nullable = false)
	public Integer getMaDm() {
		return this.maDm;
	}

	public void setMaDm(Integer maDm) {
		this.maDm = maDm;
	}

	@Column(name = "ten_dm", nullable = false, length = 50)
	public String getTenDm() {
		return this.tenDm;
	}

	public void setTenDm(String tenDm) {
		this.tenDm = tenDm;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "danhMuc")
	public Set<SanPham> getSanPhams() {
		return this.sanPhams;
	}

	public void setSanPhams(Set<SanPham> sanPhams) {
		this.sanPhams = sanPhams;
	}

}
