package App.entity;
// Generated Aug 7, 2020 10:34:01 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * HinhThucThanhToan generated by hbm2java
 */
@Entity
@Table(name = "hinh_thuc_thanh_toan", catalog = "pl9x6o2av23gjabw")
public class HinhThucThanhToan implements java.io.Serializable {

	private int maHt;
	private String hinhThuc;
	private Set<HoaDon> hoaDons = new HashSet<HoaDon>(0);

	public HinhThucThanhToan() {
	}

	public HinhThucThanhToan(int maHt) {
		this.maHt = maHt;
	}

	public HinhThucThanhToan(int maHt, String hinhThuc, Set<HoaDon> hoaDons) {
		this.maHt = maHt;
		this.hinhThuc = hinhThuc;
		this.hoaDons = hoaDons;
	}

	@Id

	@Column(name = "ma_ht", unique = true, nullable = false)
	public int getMaHt() {
		return this.maHt;
	}

	public void setMaHt(int maHt) {
		this.maHt = maHt;
	}

	@Column(name = "hinh_thuc", length = 20)
	public String getHinhThuc() {
		return this.hinhThuc;
	}

	public void setHinhThuc(String hinhThuc) {
		this.hinhThuc = hinhThuc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hinhThucThanhToan")
	public Set<HoaDon> getHoaDons() {
		return this.hoaDons;
	}

	public void setHoaDons(Set<HoaDon> hoaDons) {
		this.hoaDons = hoaDons;
	}

}
