package App.entity;
// Generated Mar 20, 2020 11:26:53 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

/**
 * HoaDonChiTiet generated by hbm2java
 */
@Entity
@Table(name = "hoa_don_chi_tiet", catalog = "management_shop")
public class HoaDonChiTiet implements java.io.Serializable {

	private Integer idHoaDonCt;
	private HoaDon hoaDon;
	private SanPham sanPham;
	private Double tongTienSp;
	private Integer soLuongSp;

	public HoaDonChiTiet() {
	}

	public HoaDonChiTiet(HoaDon hoaDon, SanPham sanPham, Double tongTienSp, Integer soLuongSp) {
		this.hoaDon = hoaDon;
		this.sanPham = sanPham;
		this.tongTienSp = tongTienSp;
		this.soLuongSp = soLuongSp;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_hoa_don_ct", unique = true, nullable = false)
	public Integer getIdHoaDonCt() {
		return this.idHoaDonCt;
	}

	public void setIdHoaDonCt(Integer idHoaDonCt) {
		this.idHoaDonCt = idHoaDonCt;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@NotFound(action = NotFoundAction.IGNORE)
	@JoinColumn(name = "id_hoa_don")
	public HoaDon getHoaDon() {
		return this.hoaDon;
	}

	public void setHoaDon(HoaDon hoaDon) {
		this.hoaDon = hoaDon;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@NotFound(action = NotFoundAction.IGNORE)
	@JoinColumn(name = "id_sp")
	public SanPham getSanPham() {
		return this.sanPham;
	}

	public void setSanPham(SanPham sanPham) {
		this.sanPham = sanPham;
	}

	@Column(name = "tong_tien_sp", precision = 22, scale = 0)
	public Double getTongTienSp() {
		return this.tongTienSp;
	}

	public void setTongTienSp(Double tongTienSp) {
		this.tongTienSp = tongTienSp;
	}

	@Column(name = "so_luong_sp")
	public Integer getSoLuongSp() {
		return this.soLuongSp;
	}

	public void setSoLuongSp(Integer soLuongSp) {
		this.soLuongSp = soLuongSp;
	}

}
