package App.entity;
// Generated Mar 20, 2020 11:26:53 AM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * HoaDon generated by hbm2java
 */
@Entity
@Table(name = "hoa_don", catalog = "management_shop")
public class HoaDon implements java.io.Serializable {

	private static final CascadeType[] ALL = null;
	private Integer maHd;
	private HinhThucThanhToan hinhThucThanhToan;
	private KhachHang khachHang;
	
	private TinhTrangHd tinhTrangHd;
	private Date thoiGianHd;
	private Set<ThongKe> thongKes = new HashSet<ThongKe>(0);
	private Set<HoaDonChiTiet> hoaDonChiTiets = new HashSet<HoaDonChiTiet>(0);

	public HoaDon() {
	}

	public HoaDon(HinhThucThanhToan hinhThucThanhToan, KhachHang khachHang, NhanVien nhanVien, TinhTrangHd tinhTrangHd,
			Date thoiGianHd) {
		this.hinhThucThanhToan = hinhThucThanhToan;
		this.khachHang = khachHang;
		
		this.tinhTrangHd = tinhTrangHd;
		this.thoiGianHd = thoiGianHd;
	}

	public HoaDon(HinhThucThanhToan hinhThucThanhToan, KhachHang khachHang, NhanVien nhanVien, TinhTrangHd tinhTrangHd,
			Date thoiGianHd, Set<ThongKe> thongKes, Set<HoaDonChiTiet> hoaDonChiTiets) {
		this.hinhThucThanhToan = hinhThucThanhToan;
		this.khachHang = khachHang;
		
		this.tinhTrangHd = tinhTrangHd;
		this.thoiGianHd = thoiGianHd;
		this.thongKes = thongKes;
		this.hoaDonChiTiets = hoaDonChiTiets;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ma_hd", unique = true, nullable = false)
	public Integer getMaHd() {
		return this.maHd;
	}

	public void setMaHd(Integer maHd) {
		this.maHd = maHd;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@NotFound(action = NotFoundAction.IGNORE)
	
	@JoinColumn(name = "ma_ht", nullable = false)
	public HinhThucThanhToan getHinhThucThanhToan() {
		return this.hinhThucThanhToan;
	}

	public void setHinhThucThanhToan(HinhThucThanhToan hinhThucThanhToan) {
		this.hinhThucThanhToan = hinhThucThanhToan;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@NotFound(action = NotFoundAction.IGNORE)
	@JoinColumn(name = "ma_kh", nullable = false)
	public KhachHang getKhachHang() {
		return this.khachHang;
	}

	public void setKhachHang(KhachHang khachHang) {
		this.khachHang = khachHang;
	}


	


	@ManyToOne(fetch = FetchType.EAGER)
	@NotFound(action = NotFoundAction.IGNORE)
	@JoinColumn(name = "tinh_trang", nullable = false)
	public TinhTrangHd getTinhTrangHd() {
		return this.tinhTrangHd;
	}

	public void setTinhTrangHd(TinhTrangHd tinhTrangHd) {
		this.tinhTrangHd = tinhTrangHd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@DateTimeFormat(pattern = "dd-MM-yyyy HH:mm:ss")
	@Column(name = "thoi_gian_hd", nullable = false, length = 19)
	public Date getThoiGianHd() {
		return this.thoiGianHd;
	}

	public void setThoiGianHd(Date thoiGianHd) {
		this.thoiGianHd = thoiGianHd;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "hoaDon")
	@NotFound(action = NotFoundAction.IGNORE)
	public Set<ThongKe> getThongKes() {
		return this.thongKes;
	}

	public void setThongKes(Set<ThongKe> thongKes) {
		this.thongKes = thongKes;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "hoaDon")
	@NotFound(action = NotFoundAction.IGNORE)
	public Set<HoaDonChiTiet> getHoaDonChiTiets() {
		return this.hoaDonChiTiets;
	}

	public void setHoaDonChiTiets(Set<HoaDonChiTiet> hoaDonChiTiets) {
		this.hoaDonChiTiets = hoaDonChiTiets;
	}

}
