package App.entity;
// Generated Mar 20, 2020 11:26:53 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

/**
 * LoaiSp generated by hbm2java
 */
@Entity
@Table(name = "loai_sp", catalog = "management_shop")
public class LoaiSp implements java.io.Serializable {

	private Integer idLoaiSp;
	private String tenLoaiSp;
	private Set<SanPham> sanPhams = new HashSet<SanPham>(0);

	public LoaiSp() {
	}

	public LoaiSp(String tenLoaiSp, Set<SanPham> sanPhams) {
		this.tenLoaiSp = tenLoaiSp;
		this.sanPhams = sanPhams;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_loai_sp", unique = true, nullable = false)
	public Integer getIdLoaiSp() {
		return this.idLoaiSp;
	}

	public void setIdLoaiSp(Integer idLoaiSp) {
		this.idLoaiSp = idLoaiSp;
	}

	@Column(name = "ten_loai_sp", length = 45)
	public String getTenLoaiSp() {
		return this.tenLoaiSp;
	}

	public void setTenLoaiSp(String tenLoaiSp) {
		this.tenLoaiSp = tenLoaiSp;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "loaiSp")
	@NotFound(action = NotFoundAction.IGNORE)
	public Set<SanPham> getSanPhams() {
		return this.sanPhams;
	}

	public void setSanPhams(Set<SanPham> sanPhams) {
		this.sanPhams = sanPhams;
	}

}
