package App.entity;
// Generated Aug 7, 2020 10:34:01 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NhanVien generated by hbm2java
 */
@Entity
@Table(name = "nhan_vien", catalog = "pl9x6o2av23gjabw")
public class NhanVien implements java.io.Serializable {

	private Integer maNv;
	private PhanQuyen phanQuyen;
	private String tenNv;
	private Integer sdtNv;
	private String emailNv;
	private int cmndNv;
	private Date ngaySinhNv;
	private String diaChiNv;
	private String tenDangNhapNv;
	private String matKhauNv;
	private Set<ConfirmationToken> confirmationTokens = new HashSet<ConfirmationToken>(0);

	public NhanVien() {
	}

	public NhanVien(PhanQuyen phanQuyen, String tenNv, String emailNv, int cmndNv, String tenDangNhapNv,
			String matKhauNv) {
		this.phanQuyen = phanQuyen;
		this.tenNv = tenNv;
		this.emailNv = emailNv;
		this.cmndNv = cmndNv;
		this.tenDangNhapNv = tenDangNhapNv;
		this.matKhauNv = matKhauNv;
	}

	public NhanVien(PhanQuyen phanQuyen, String tenNv, Integer sdtNv, String emailNv, int cmndNv, Date ngaySinhNv,
			String diaChiNv, String tenDangNhapNv, String matKhauNv, Set<ConfirmationToken> confirmationTokens) {
		this.phanQuyen = phanQuyen;
		this.tenNv = tenNv;
		this.sdtNv = sdtNv;
		this.emailNv = emailNv;
		this.cmndNv = cmndNv;
		this.ngaySinhNv = ngaySinhNv;
		this.diaChiNv = diaChiNv;
		this.tenDangNhapNv = tenDangNhapNv;
		this.matKhauNv = matKhauNv;
		this.confirmationTokens = confirmationTokens;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ma_nv", unique = true, nullable = false)
	public Integer getMaNv() {
		return this.maNv;
	}

	public void setMaNv(Integer maNv) {
		this.maNv = maNv;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ma_phan_quyen", nullable = false)
	public PhanQuyen getPhanQuyen() {
		return this.phanQuyen;
	}

	public void setPhanQuyen(PhanQuyen phanQuyen) {
		this.phanQuyen = phanQuyen;
	}

	@Column(name = "ten_nv", nullable = false, length = 50)
	public String getTenNv() {
		return this.tenNv;
	}

	public void setTenNv(String tenNv) {
		this.tenNv = tenNv;
	}

	@Column(name = "sdt_nv")
	public Integer getSdtNv() {
		return this.sdtNv;
	}

	public void setSdtNv(Integer sdtNv) {
		this.sdtNv = sdtNv;
	}

	@Column(name = "email_nv", nullable = false, length = 50)
	public String getEmailNv() {
		return this.emailNv;
	}

	public void setEmailNv(String emailNv) {
		this.emailNv = emailNv;
	}

	@Column(name = "cmnd_nv", nullable = false)
	public int getCmndNv() {
		return this.cmndNv;
	}

	public void setCmndNv(int cmndNv) {
		this.cmndNv = cmndNv;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ngay_sinh_nv", length = 10)
	public Date getNgaySinhNv() {
		return this.ngaySinhNv;
	}

	public void setNgaySinhNv(Date ngaySinhNv) {
		this.ngaySinhNv = ngaySinhNv;
	}

	@Column(name = "dia_chi_nv", length = 500)
	public String getDiaChiNv() {
		return this.diaChiNv;
	}

	public void setDiaChiNv(String diaChiNv) {
		this.diaChiNv = diaChiNv;
	}

	@Column(name = "ten_dang_nhap_nv", nullable = false, length = 20)
	public String getTenDangNhapNv() {
		return this.tenDangNhapNv;
	}

	public void setTenDangNhapNv(String tenDangNhapNv) {
		this.tenDangNhapNv = tenDangNhapNv;
	}

	@Column(name = "mat_khau_nv", nullable = false, length = 100)
	public String getMatKhauNv() {
		return this.matKhauNv;
	}

	public void setMatKhauNv(String matKhauNv) {
		this.matKhauNv = matKhauNv;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nhanVien")
	public Set<ConfirmationToken> getConfirmationTokens() {
		return this.confirmationTokens;
	}

	public void setConfirmationTokens(Set<ConfirmationToken> confirmationTokens) {
		this.confirmationTokens = confirmationTokens;
	}

}
