package App.entity;
// Generated Mar 20, 2020 11:26:53 AM by Hibernate Tools 5.2.12.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Past;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;
import org.springframework.format.annotation.DateTimeFormat;

/**
 * NhanVien generated by hbm2java
 */
@Entity
@Table(name = "nhan_vien", catalog = "management_shop")
public class NhanVien implements java.io.Serializable {

	private Integer maNv;
	private PhanQuyen phanQuyen;
	private String tenNv;
	private int sdtNv;
	private String emailNv;
	private int cmndNv;
	private Date ngaySinhNv;
	private String diaChiNv;
	private String tenDangNhapNv;
	private String matKhauNv;
	

	public NhanVien() {
	}

	public NhanVien(PhanQuyen phanQuyen, String tenNv, int sdtNv, String emailNv, int cmndNv, String tenDangNhapNv,
			String matKhauNv) {
		this.phanQuyen = phanQuyen;
		this.tenNv = tenNv;
		this.sdtNv = sdtNv;
		this.emailNv = emailNv;
		this.cmndNv = cmndNv;
		this.tenDangNhapNv = tenDangNhapNv;
		this.matKhauNv = matKhauNv;
	}

	public NhanVien(PhanQuyen phanQuyen, String tenNv, int sdtNv, String emailNv, int cmndNv, Date ngaySinhNv,
			String diaChiNv, String tenDangNhapNv, String matKhauNv, Set<HoaDon> hoaDons) {
		this.phanQuyen = phanQuyen;
		this.tenNv = tenNv;
		this.sdtNv = sdtNv;
		this.emailNv = emailNv;
		this.cmndNv = cmndNv;
		this.ngaySinhNv = ngaySinhNv;
		this.diaChiNv = diaChiNv;
		this.tenDangNhapNv = tenDangNhapNv;
		this.matKhauNv = matKhauNv;
		
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ma_nv", unique = true, nullable = false)
	public Integer getMaNv() {
		return this.maNv;
	}

	public void setMaNv(Integer maNv) {
		this.maNv = maNv;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	
	@JoinColumn(name = "ma_phan_quyen", nullable = false)
	public PhanQuyen getPhanQuyen() {
		return this.phanQuyen;
	}

	public void setPhanQuyen(PhanQuyen phanQuyen) {
		this.phanQuyen = phanQuyen;
	}

	@Column(name = "ten_nv", nullable = false, length = 50)
	public String getTenNv() {
		return this.tenNv;
	}

	public void setTenNv(String tenNv) {
		this.tenNv = tenNv;
	}

	@Column(name = "sdt_nv", nullable = false)
	public int getSdtNv() {
		return this.sdtNv;
	}

	public void setSdtNv(int sdtNv) {
		this.sdtNv = sdtNv;
	}

	@Column(name = "email_nv", nullable = false, length = 50)
	public String getEmailNv() {
		return this.emailNv;
	}

	public void setEmailNv(String emailNv) {
		this.emailNv = emailNv;
	}

	@Column(name = "cmnd_nv", nullable = false)
	public int getCmndNv() {
		return this.cmndNv;
	}

	public void setCmndNv(int cmndNv) {
		this.cmndNv = cmndNv;
	}
	@Past
	@Temporal(TemporalType.DATE)
	@DateTimeFormat(pattern = "dd-MM-yyyy")
	@Column(name = "ngay_sinh_nv", length = 10)
	public Date getNgaySinhNv() {
		return this.ngaySinhNv;
	}

	public void setNgaySinhNv(Date ngaySinhNv) {
		this.ngaySinhNv = ngaySinhNv;
	}

	@Column(name = "dia_chi_nv", length = 500)
	public String getDiaChiNv() {
		return this.diaChiNv;
	}

	public void setDiaChiNv(String diaChiNv) {
		this.diaChiNv = diaChiNv;
	}

	@Column(name = "ten_dang_nhap_nv", nullable = false, length = 20)
	public String getTenDangNhapNv() {
		return this.tenDangNhapNv;
	}

	public void setTenDangNhapNv(String tenDangNhapNv) {
		this.tenDangNhapNv = tenDangNhapNv;
	}

	@Column(name = "mat_khau_nv", nullable = false, length = 20)
	public String getMatKhauNv() {
		return this.matKhauNv;
	}

	public void setMatKhauNv(String matKhauNv) {
		this.matKhauNv = matKhauNv;
	}
}
