package App.entity;
// Generated Mar 20, 2020 11:26:53 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PhamVi generated by hbm2java
 */
@Entity
@Table(name = "pham_vi", catalog = "management_shop")
public class PhamVi implements java.io.Serializable {

	private Integer maPv;
	private String phamVi;
	private Set<ThongKe> thongKes = new HashSet<ThongKe>(0);

	public PhamVi() {
	}

	public PhamVi(String phamVi) {
		this.phamVi = phamVi;
	}

	public PhamVi(String phamVi, Set<ThongKe> thongKes) {
		this.phamVi = phamVi;
		this.thongKes = thongKes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ma_pv", unique = true, nullable = false)
	public Integer getMaPv() {
		return this.maPv;
	}

	public void setMaPv(Integer maPv) {
		this.maPv = maPv;
	}

	@Column(name = "pham_vi", nullable = false, length = 20)
	public String getPhamVi() {
		return this.phamVi;
	}

	public void setPhamVi(String phamVi) {
		this.phamVi = phamVi;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "phamVi")
	public Set<ThongKe> getThongKes() {
		return this.thongKes;
	}

	public void setThongKes(Set<ThongKe> thongKes) {
		this.thongKes = thongKes;
	}

}
