package App.entity;
// Generated Aug 7, 2020 10:34:01 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PhanQuyen generated by hbm2java
 */
@Entity
@Table(name = "phan_quyen", catalog = "pl9x6o2av23gjabw")
public class PhanQuyen implements java.io.Serializable {

	private Integer maPhanQuyen;
	private String tenPhanQuyen;
	private Set<NhanVien> nhanViens = new HashSet<NhanVien>(0);

	public PhanQuyen() {
	}

	public PhanQuyen(String tenPhanQuyen) {
		this.tenPhanQuyen = tenPhanQuyen;
	}

	public PhanQuyen(String tenPhanQuyen, Set<NhanVien> nhanViens) {
		this.tenPhanQuyen = tenPhanQuyen;
		this.nhanViens = nhanViens;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ma_phan_quyen", unique = true, nullable = false)
	public Integer getMaPhanQuyen() {
		return this.maPhanQuyen;
	}

	public void setMaPhanQuyen(Integer maPhanQuyen) {
		this.maPhanQuyen = maPhanQuyen;
	}

	@Column(name = "ten_phan_quyen", nullable = false, length = 20)
	public String getTenPhanQuyen() {
		return this.tenPhanQuyen;
	}

	public void setTenPhanQuyen(String tenPhanQuyen) {
		this.tenPhanQuyen = tenPhanQuyen;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "phanQuyen")
	public Set<NhanVien> getNhanViens() {
		return this.nhanViens;
	}

	public void setNhanViens(Set<NhanVien> nhanViens) {
		this.nhanViens = nhanViens;
	}

}
