package App.entity;
// Generated Mar 20, 2020 11:26:53 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

/**
 * PhanQuyen generated by hbm2java
 */
@Entity
@Table(name = "phan_quyen", catalog = "management_shop")
public class PhanQuyen implements java.io.Serializable {

	private Integer maPhanQuyen;
	@NotNull(message = "Vui Lòng Nhập Tên Danh Mục")
	
	@NotBlank(message = "Vui Lòng Nhập Tên Danh Mục")
	private String tenPhanQuyen;
	private Set<NhanVien> nhanViens = new HashSet<NhanVien>(0);

	public PhanQuyen() {
	}

	public PhanQuyen(String tenPhanQuyen,int maPhanQuyen) {
		super();
		this.tenPhanQuyen = tenPhanQuyen;
		this.maPhanQuyen=maPhanQuyen;
	}

	public PhanQuyen(String tenPhanQuyen, Set<NhanVien> nhanViens) {
		this.tenPhanQuyen = tenPhanQuyen;
		this.nhanViens = nhanViens;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ma_phan_quyen", unique = true, nullable = false)
	public Integer getMaPhanQuyen() {
		return this.maPhanQuyen;
	}

	public void setMaPhanQuyen(Integer maPhanQuyen) {
		this.maPhanQuyen = maPhanQuyen;
	}

	@Column(name = "ten_phan_quyen", nullable = false, length = 20)
	public String getTenPhanQuyen() {
		return this.tenPhanQuyen;
	}

	public void setTenPhanQuyen(String tenPhanQuyen) {
		this.tenPhanQuyen = tenPhanQuyen;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "phanQuyen")
	public Set<NhanVien> getNhanViens() {
		return this.nhanViens;
	}

	public void setNhanViens(Set<NhanVien> nhanViens) {
		this.nhanViens = nhanViens;
	}

}
